[CUSTOM]
%23%200=Content
%23%201=Expressive
%23%202=Fidelity
%23%203=Monochrome
%23%204=Neutral
%23%205=TonalSpot
%23%206=Vibrant
%23%207=Rainbow
%23%208=FruitSalad
%23%20qdbus_executable=qdbus6
%23color=255, 0, 1
%23custom_colors_list=#ED8796 #A6DA95 #EED49F #8AADF4 #F5BDE6 #8BD5CA #f5a97f
%23dark_blend_multiplier=1.0
%23darker_window_list=konsole Alacritty kitty
%23disable_konsole=False
%23file=/tmp/000_eDP-1_current_wallpaper
%23iconsdark=Papirus-Dark
%23iconslight=Papirus-Light
%23klassy_windeco_outline=True
%23konsole_blur=False
%23konsole_opacity=85
%23konsole_opacity_dark=85
%23light=False
%23light_blend_multiplier=1.0
%23main_loop_delay=1
%23on_change_hook=
%23once_after_change=False
%23pause_mode=False
%23pywal=True
%23pywal_light=False
%23screenshot_delay=900
%23sierra_breeze_buttons_color=True
%23startup_delay=5
%23titlebar_opacity=85
%23titlebar_opacity_dark=85
%23titlebar_opacity_override=False
%23toolbar_opacity=85
%23toolbar_opacity_dark=85
%23use_startup_delay=True
chroma_multiplier=1
color=
color_last=#d0265c
contrast_level=0
custom_colors_list=
custom_colors_list_last=#d0265c #74e448 #eece4f #66a3ef #532066 #297d81 #ccc1c1
dark_brightness_multiplier=1
dark_saturation_multiplier=1
darker_window_list=
disable_konsole=false
fetch_colors=false
frame_contrast=0.2
gui_custom_exec_location=
iconsdark=breeze-plus-dark
iconslight=breeze-plus
kde_rounded_corners_effect_outline=false
klassy_windeco_outline=false
konsole_blur=false
konsole_opacity=100
konsole_opacity_dark=100
light=false
light_brightness_multiplier=1
light_saturation_multiplier=1
main_loop_delay=1
manual_fetch=false
monitor=0
ncolor=0
on_change_hook=
once_after_change=false
pause_mode=false
plasma_follows_scheme=false
pywal=true
pywal_follows_scheme=false
pywal_light=false
scheme_variant=6
screenshot_delay=900
screenshot_only_mode=false
sierra_breeze_buttons_color=false
spec_version=2025
startup_delay=0
titlebar_opacity=100
titlebar_opacity_dark=100
titlebar_opacity_override=false
tone_multiplier=1
toolbar_opacity=100
toolbar_opacity_dark=100
use_startup_delay=false
