# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1f010c"

# Main text color
theme[main_fg]="#f9d3dc"

# Title color for boxes
theme[title]="#f9d3dc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bbafc0"

# Background color of selected item in processes box
theme[selected_bg]="#c6b2c0"

# Foreground color of selected item in processes box
theme[selected_fg]="#f9d3dc"

# Color of inactive/disabled text
theme[inactive_fg]="#a4938c"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#f9d3dc"

# Background color of the percentage meters
theme[meter_bg]="#45161b"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e6a2a7"

# Cpu box outline color
theme[cpu_box]="#a7a8c3"

# Memory/disks box outline color
theme[mem_box]="#b1abba"

# Net up/down box outline color
theme[net_box]="#e19499"

# Processes box outline color
theme[proc_box]="#d6c4c9"

# Box divider line and small boxes line color
theme[div_line]="#4b333c"

# Temperature graph colors
theme[temp_start]="#b2b3cb"
theme[temp_mid]="#bbb6c3"
theme[temp_end]="#dccbd0"

# CPU graph colors
theme[cpu_start]="#b2b3cb"
theme[cpu_mid]="#bbb6c3"
theme[cpu_end]="#dccbd0"

# Mem/Disk free meter
theme[free_start]="#b2b3cb"
theme[free_mid]="#bbb6c3"
theme[free_end]="#dccbd0"

# Mem/Disk cached meter
theme[cached_start]="#b2b3cb"
theme[cached_mid]="#bbb6c3"
theme[cached_end]="#dccbd0"

# Mem/Disk available meter
theme[available_start]="#b2b3cb"
theme[available_mid]="#bbb6c3"
theme[available_end]="#dccbd0"

# Mem/Disk used meter
theme[used_start]="#b2b3cb"
theme[used_mid]="#bbb6c3"
theme[used_end]="#dccbd0"

# Download graph colors
theme[download_start]="#b2b3cb"
theme[download_mid]="#bbb6c3"
theme[download_end]="#dccbd0"

# Upload graph colors
theme[upload_start]="#b2b3cb"
theme[upload_mid]="#bbb6c3"
theme[upload_end]="#dccbd0"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#b2b3cb"
theme[process_mid]="#bbb6c3"
theme[process_end]="#dccbd0"
