[colors]
ansi = [
    "#1f010c",
    "#b1a4b6",
    "#e19499",
    "#a7a8c3",
    "#bea7b6",
    "#b1abba",
    "#d6c4c9",
    "#dbc4bb",
]
background = "#1f010c"
brights = [
    "#cda7b0",
    "#bbafc0",
    "#e6a2a7",
    "#b2b3cb",
    "#c6b2c0",
    "#bbb6c3",
    "#dccbd0",
    "#e0cbc4",
]
cursor_bg = "#ffdde5"
cursor_border = "#ffdde5"
cursor_fg = "#1f010c"
foreground = "#f9d3dc"
selection_bg = "#bea7b6"
selection_fg = "#1f010c"

