--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/inder/Pictures/Pictures/wallpaperflare.com_wallpaper(1) (1).jpg"

-- Special
background="#1f010c"
foreground="#f9d3dc"
cursor="#ffdde5"

-- Colors
color0="#1f010c"
color1="#b1a4b6"
color2="#e19499"
color3="#a7a8c3"
color4="#bea7b6"
color5="#b1abba"
color6="#d6c4c9"
color7="#dbc4bb"
color8="#cda7b0"
color9="#bbafc0"
color10="#e6a2a7"
color11="#b2b3cb"
color12="#c6b2c0"
color13="#bbb6c3"
color14="#dccbd0"
color15="#e0cbc4"
