[colors]
background = '#1f010c8e'
black = '#1f010c'
blue = '#b1a4b6'
cursor = '#ffdde5'
cyan = '#e19499'
foreground = '#f9d3dc'
green = '#a7a8c3'
magenta = '#bea7b6'
red = '#b1abba'
tabs = '#f9d3dc'
tabs-active = '#d6c4c9'
white = '#f9d3dc'
yellow = '#dbc4bb'
dim-black = '#1f010c8e'
dim-blue = '#b1a4b68e'
dim-cyan = '#e194998e'
dim-foreground = '#f9d3dc8e'
dim-green = '#a7a8c38e'
dim-magenta = '#bea7b68e'
dim-red = '#b1abba8e'
dim-white = '#d6c4c98e'
dim-yellow = '#dbc4bb8e'
light-black = '#bbafc0'
light-blue = '#e6a2a7'
light-cyan = '#b2b3cb'
light-foreground = '#c6b2c0'
light-green = '#bbb6c3'
light-magenta = '#dccbd0'
light-red = '#e0cbc4'
light-white = '#bbafc0'
light-yellow = '#e6a2a7'
