# pywal theme for ghostty

background = 1f010c
foreground = f9d3dc
cursor-color = ffdde5
selection-background = f9d3dc
selection-foreground = 1f010c

palette = 0=#1f010c
palette = 1=#b1a4b6
palette = 2=#e19499
palette = 3=#a7a8c3
palette = 4=#bea7b6
palette = 5=#b1abba
palette = 6=#d6c4c9
palette = 7=#dbc4bb
palette = 8=#cda7b0
palette = 9=#bbafc0
palette = 10=#e6a2a7
palette = 11=#b2b3cb
palette = 12=#c6b2c0
palette = 13=#bbb6c3
palette = 14=#dccbd0
palette = 15=#e0cbc4
